name: honeywell_scanner
description: This is a plugin to scan barcodes by using Honeywell PDA Android devices.
version: 4.0.0+14
homepage: https://github.com/luis901101/honeywell_scanner

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.flutter.honeywell_scanner
        pluginClass: HoneywellScannerPlugin
